"""initial_schema

Revision ID: ce4a8051b8d0
Revises: 
Create Date: 2026-01-16 20:02:56.720564

"""
from alembic import op
import sqlalchemy as sa


revision = 'ce4a8051b8d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('design_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('iec_62304_class', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_projects_id'), 'design_projects', ['id'], unique=False)
    op.create_index(op.f('ix_design_projects_project_code'), 'design_projects', ['project_code'], unique=True)
    op.create_table('electronic_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('signature_meaning', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electronic_signatures_id'), 'electronic_signatures', ['id'], unique=False)
    op.create_table('traceability_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_links_id'), 'traceability_links', ['id'], unique=False)
    op.create_index(op.f('ix_traceability_links_source_id'), 'traceability_links', ['source_id'], unique=False)
    op.create_index(op.f('ix_traceability_links_source_type'), 'traceability_links', ['source_type'], unique=False)
    op.create_index(op.f('ix_traceability_links_target_id'), 'traceability_links', ['target_id'], unique=False)
    op.create_index(op.f('ix_traceability_links_target_type'), 'traceability_links', ['target_type'], unique=False)
    op.create_table('design_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_number', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('figma_link', sa.Text(), nullable=True),
    sa.Column('gdocs_link', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=50), nullable=True),
    sa.Column('current_assignee', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_assignee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_changes_change_number'), 'design_changes', ['change_number'], unique=True)
    op.create_index(op.f('ix_design_changes_id'), 'design_changes', ['id'], unique=False)
    op.create_index(op.f('ix_design_changes_workflow_status'), 'design_changes', ['workflow_status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_code', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('gdrive_file_id', sa.String(length=255), nullable=True),
    sa.Column('gdrive_file_path', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_code'),
    sa.UniqueConstraint('gdrive_file_id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('risk_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_number', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hazard', sa.Text(), nullable=False),
    sa.Column('hazardous_situation', sa.Text(), nullable=True),
    sa.Column('harm', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('control_measures', sa.Text(), nullable=True),
    sa.Column('residual_risk_level', sa.String(length=20), nullable=True),
    sa.Column('excel_file_id', sa.String(length=255), nullable=True),
    sa.Column('excel_row_number', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_number')
    )
    op.create_index(op.f('ix_risk_items_id'), 'risk_items', ['id'], unique=False)
    op.create_table('agent_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('affected_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['design_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_analysis_id'), 'agent_analysis', ['id'], unique=False)
    op.create_table('change_risk_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('requires_reassessment', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['design_changes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_risk_links_id'), 'change_risk_links', ['id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['design_changes.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_id'), 'workflow_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_history_id'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_change_risk_links_id'), table_name='change_risk_links')
    op.drop_table('change_risk_links')
    op.drop_index(op.f('ix_agent_analysis_id'), table_name='agent_analysis')
    op.drop_table('agent_analysis')
    op.drop_index(op.f('ix_risk_items_id'), table_name='risk_items')
    op.drop_table('risk_items')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_design_changes_workflow_status'), table_name='design_changes')
    op.drop_index(op.f('ix_design_changes_id'), table_name='design_changes')
    op.drop_index(op.f('ix_design_changes_change_number'), table_name='design_changes')
    op.drop_table('design_changes')
    op.drop_index(op.f('ix_traceability_links_target_type'), table_name='traceability_links')
    op.drop_index(op.f('ix_traceability_links_target_id'), table_name='traceability_links')
    op.drop_index(op.f('ix_traceability_links_source_type'), table_name='traceability_links')
    op.drop_index(op.f('ix_traceability_links_source_id'), table_name='traceability_links')
    op.drop_index(op.f('ix_traceability_links_id'), table_name='traceability_links')
    op.drop_table('traceability_links')
    op.drop_index(op.f('ix_electronic_signatures_id'), table_name='electronic_signatures')
    op.drop_table('electronic_signatures')
    op.drop_index(op.f('ix_design_projects_project_code'), table_name='design_projects')
    op.drop_index(op.f('ix_design_projects_id'), table_name='design_projects')
    op.drop_table('design_projects')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
